server:
  port: 8022
  servlet:
    session:
      timeout: 1200s  # 20分钟
spring:
  application:
    name: mem-parent
  redis:
    database: 0           # Redis服务器数据库
    host: 192.168.231.141    # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    # password: glf      # Redis服务器连接密码（默认为空）
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root # 5333592Zhang # 123456                127.0.0.1               cpoc_model_equipment
    url: jdbc:mysql://192.168.231.141:3306/mem-parent?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # url: jdbc:mysql://101.132.170.184:3306/ruoyi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    druid:
      initial-size: 1
      min-idle: 1 #最小空闲连接
      max-active: 20 #最大活动连接
      test-on-borrow: true #获取连接时测试是否可用
      stat-view-servlet.allow: true #监控页面启动
mybatis:
  # mybatis 别名扫描
  type-aliases-package: com.wbr.model.mem.vo
  # mapper.xml文件位置,如果没有映射文件，请注释掉
  mapper-locations:  classpath:com.wbr./**/dao/*.xml
